
c:\Python27\data_migrator_1239_mongo>echo y  | c:\Python27\qc_dist_32\20150723_234254\qc32\qc32.exe -w SS2016-SSEXP -o 1 -r 1 -t "|" -l 25 -K 1 -M C:\Temp\qc_log -F C:\tmp\TEST_default_spool -B qc_job -Y 20150723_234254_232000 -5 ".\config\host_map\host_map.py" -6 csv -dbg 1 -Q c:\Python27\data_migrator_1239_mongo\test\v101\query\query_dir_ss -j sa -x ssent_pwd -b test -n ALEX_BUZ-PC\MSSQLSERVER_ENT -z "C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn" -u sa -p 198Morgan -d master -s ALEX_BUZ-PC\SQLEXPRESS -a dbo.Timestamp_test_to -Z "C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn" 
----------------------------------------------------------------------
QueryCopy for SQL Server Express (v0.3.5, beta, 2015/07/23 23:42:54) [32bit]
Copyright (c): 2014 Alex Buzunov, All rights reserved.
Agreement: Use this tool at your own risk. Author is not liable for any damages or losses related to the use of this software.
----------------------------------------------------------------------
<class 'pipeline.v101.to_sqlserver.ToSQLServer'>
####################
Performing data copy.
		
	From SQL Server 2016:	
		from db: sa/test/ALEX_BUZ-PC\MSSQLSERVER_ENT
		query dir: c:\Python27\data_migrator_1239_mongo\test\v101\query\query_dir_ss
		shards:	3
		
		
	To SQLServer:	
		to db: sa/master/ALEX_BUZ-PC\SQLEXPRESS
		to table: dbo.Timestamp_test_to
		
####################
Are you sure you want to proceed?(y/n): 
spID 0
Unexpected error: (<type 'exceptions.IOError'>, IOError(9, 'Bad file descriptor'), <traceback object at 0x0333A148>)
2015-07-23 23:44:17,098 - SS2016-SSEXP - WARNING - Overriding num_of_shards (1) to be equal number of queries (3).
2015-07-23 23:44:17,108 - SS2016-SSEXP - INFO - Fetching query columns...
Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : TCP Provider: No connection could be made because the target machine actively refused it.
.
Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
Traceback (most recent call last):
  File "<string>", line 343, in <module>
  File "c:\Python27\data_migrator_1239_mongo\build\qc32\out00-PYZ.pyz\template.v101.spool_and_load", line 174, in set_payload
  File "c:\Python27\data_migrator_1239_mongo\build\qc32\out00-PYZ.pyz\pipeline.v101.from_sqlserver", line 235, in set_payload
  File "c:\Python27\data_migrator_1239_mongo\build\qc32\out00-PYZ.pyz\pipeline.v101.from_sqlserver", line 333, in set_querylist_payload
  File "c:\Python27\data_migrator_1239_mongo\build\qc32\out00-PYZ.pyz\db.v101.db_sqlserver", line 298, in get_query_columns
NameError: global name 't' is not defined
